### ISSUE TITLE
Pass The Ticket and cert support

### ISSUE THREAD

**Issue by CravateRouge** [skelsec/aardwolfgui#1]
Hi, 

Will it support providing a kerberos ticket or a x509 certificate? I think it can be really interesting when we only have a ticket/cert during our assessments. 

Thank you for bringing this tool to the community!

**Comment by skelsec** [comment]
Thank you for the kind words, however I do not understand what exactly you are missing in kerberos?
This project supports kerberos authentication with password/rc4/aes128/aes256/kiribi/p12

**Comment by CravateRouge** [comment]
I must admit I didn't read the code and just went through the README without seeing those authentications so I assumed it was missing ^^'
